package com.axiom.domain.triage;

public enum ActionType {
    RERUN_PIPELINE,
    INSPECT_INFRASTRUCTURE,
    INSPECT_DEPENDENCY_CONFIGURATION,
    INSPECT_BUILD,
    INSPECT_TEST,
    INSPECT_SOURCE_CHANGE,
    INSPECT_CONFIGURATION,
    INSPECT_EXTERNAL_SERVICE,
    INSPECT_RESOURCES,
    REVIEW_FAILURE_DETAILS
}
