package com.axiom.domain.failure;

public enum FailureClassification { PRODUCT_REGRESSION, TEST_FAILURE, FLAKY_TEST, DEPENDENCY_FAILURE, BUILD_FAILURE, ENVIRONMENT_FAILURE, INFRASTRUCTURE_FAILURE, CONFIGURATION_FAILURE, TIMEOUT, RESOURCE_EXHAUSTION, EXTERNAL_SERVICE_FAILURE, UNKNOWN }
