package com.axiom.api.controller;
import com.axiom.api.dto.*; import com.axiom.application.pipeline.*; import com.axiom.application.analysis.*; import jakarta.validation.Valid; import java.util.List; import java.util.UUID; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/pipeline-runs") public class PipelineRunController {
 private final PipelineIngestionService ingestion; private final JdbcTemplate jdbc; private final PipelineLogAnalysisService logAnalysis; private final PipelineDiagnosisService diagnoses; public PipelineRunController(PipelineIngestionService ingestion,JdbcTemplate jdbc,PipelineLogAnalysisService logAnalysis,PipelineDiagnosisService diagnoses){this.ingestion=ingestion;this.jdbc=jdbc;this.logAnalysis=logAnalysis;this.diagnoses=diagnoses;}
 @PostMapping("/ingest") @ResponseStatus(HttpStatus.CREATED) public PipelineRunResponse ingest(@Valid @RequestBody PipelineIngestRequest r){PersistedPipelineRun saved=ingestion.ingest(new PipelineRunReference(r.provider(),r.repositoryOwner(),r.repositoryName(),r.externalRunId()));return find(saved.id());}
 @GetMapping("/{id}") public PipelineRunResponse get(@PathVariable UUID id){return find(id);}
 @GetMapping("/github/{owner}/{repository}/{runId}") public List<PipelineRunResponse> github(@PathVariable String owner,@PathVariable String repository,@PathVariable long runId){return jdbc.query("select pr.id from pipeline_runs pr join repositories r on r.id=pr.repository_id where r.provider='GITHUB_ACTIONS' and r.owner=? and r.name=? and pr.external_run_id=? order by pr.attempt",(rs,n)->find((UUID)rs.getObject(1)),owner,repository,runId);}
 @GetMapping("/{id}/logs") public Object logMetadata(@PathVariable UUID id){return jdbc.query("select id,size_bytes,sha256,created_at from pipeline_logs where pipeline_run_id=?",rs->{if(!rs.next())throw new IllegalArgumentException("No stored log for pipeline run "+id);return java.util.Map.of("id",rs.getObject(1),"sizeBytes",rs.getLong(2),"sha256",rs.getString(3),"createdAt",rs.getObject(4));},id);}
 @PostMapping("/{id}/process-logs") public Object processLogs(@PathVariable UUID id){return logAnalysis.process(id);}
 @GetMapping("/{id}/failures") public Object failures(@PathVariable UUID id){return jdbc.queryForList("select fingerprint,fingerprint_algorithm,event_type,exception_type,normalized_message,occurrence_count,first_line,last_line from failure_events where pipeline_run_id=? order by first_line",id);}
 @GetMapping("/{id}/failures/{fingerprint}") public Object failure(@PathVariable UUID id,@PathVariable String fingerprint){return jdbc.query("select fingerprint,fingerprint_algorithm,event_type,exception_type,normalized_message,stack_trace,occurrence_count,first_line,last_line from failure_events where pipeline_run_id=? and fingerprint=?",rs->{if(!rs.next())throw new IllegalArgumentException("Failure fingerprint was not found.");return java.util.Map.of("fingerprint",rs.getString(1),"fingerprintAlgorithm",rs.getString(2),"type",rs.getString(3),"exceptionType",java.util.Optional.ofNullable(rs.getString(4)).orElse(""),"normalizedMessage",rs.getString(5),"stackTrace",java.util.Optional.ofNullable(rs.getString(6)).orElse(""),"occurrences",rs.getInt(7),"firstLine",rs.getInt(8),"lastLine",rs.getInt(9));},id,fingerprint);}
 @PostMapping("/{id}/diagnose") public Object diagnose(@PathVariable UUID id){return diagnoses.diagnose(id);}
 @GetMapping("/{id}/diagnoses") public Object diagnoses(@PathVariable UUID id){return jdbc.queryForList("select fingerprint,classification,confidence,confidence_level,summary,classifier_version from failure_diagnoses where pipeline_run_id=?",id);}
 @GetMapping("/{id}/diagnoses/{fingerprint}") public Object diagnosis(@PathVariable UUID id,@PathVariable String fingerprint){return jdbc.queryForMap("select fingerprint,classification,confidence,confidence_level,summary,probable_cause,recommended_action,classifier_version from failure_diagnoses where pipeline_run_id=? and fingerprint=?",id,fingerprint);}
 private PipelineRunResponse find(UUID id){return jdbc.query("select pr.id,r.provider,r.owner,r.name,pr.external_run_id,pr.attempt,pr.status,pr.conclusion,pr.commit_sha,pr.branch,pr.pull_request_number,pr.ingested_at,(select count(*) from pipeline_jobs j where j.pipeline_run_id=pr.id),(select count(*) from pipeline_steps s join pipeline_jobs j on s.pipeline_job_id=j.id where j.pipeline_run_id=pr.id) from pipeline_runs pr join repositories r on r.id=pr.repository_id where pr.id=?",rs->{if(!rs.next())throw new IllegalArgumentException("Pipeline run "+id+" was not found.");return new PipelineRunResponse((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getLong(5),rs.getInt(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),(Long)rs.getObject(11),rs.getInt(13),rs.getInt(14),rs.getObject(12,java.time.Instant.class));},id);}
}
