package com.axiom.api.controller;
import com.axiom.api.dto.*; import com.axiom.application.pipeline.*; import com.axiom.domain.pipeline.CiProviderType; import jakarta.validation.Valid; import java.util.List; import java.util.UUID; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/pipeline-runs") public class PipelineRunController {
 private final PipelineIngestionService ingestion; private final JdbcTemplate jdbc; public PipelineRunController(PipelineIngestionService ingestion,JdbcTemplate jdbc){this.ingestion=ingestion;this.jdbc=jdbc;}
 @PostMapping("/ingest") @ResponseStatus(HttpStatus.CREATED) public PipelineRunResponse ingest(@Valid @RequestBody PipelineIngestRequest r){PersistedPipelineRun saved=ingestion.ingest(new PipelineRunReference(r.provider(),r.repositoryOwner(),r.repositoryName(),r.externalRunId()));return find(saved.id());}
 @GetMapping("/{id}") public PipelineRunResponse get(@PathVariable UUID id){return find(id);}
 @GetMapping("/github/{owner}/{repository}/{runId}") public List<PipelineRunResponse> github(@PathVariable String owner,@PathVariable String repository,@PathVariable long runId){return jdbc.query("select pr.id from pipeline_runs pr join repositories r on r.id=pr.repository_id where r.provider='GITHUB_ACTIONS' and r.owner=? and r.name=? and pr.external_run_id=? order by pr.attempt",(rs,n)->find((UUID)rs.getObject(1)),owner,repository,runId);}
 @GetMapping("/{id}/logs") public Object logMetadata(@PathVariable UUID id){return jdbc.query("select id,size_bytes,sha256,created_at from pipeline_logs where pipeline_run_id=?",rs->{if(!rs.next())throw new IllegalArgumentException("No stored log for pipeline run "+id);return java.util.Map.of("id",rs.getObject(1),"sizeBytes",rs.getLong(2),"sha256",rs.getString(3),"createdAt",rs.getObject(4));},id);}
 private PipelineRunResponse find(UUID id){return jdbc.query("select pr.id,r.provider,r.owner,r.name,pr.external_run_id,pr.attempt,pr.status,pr.conclusion,pr.commit_sha,pr.branch,pr.pull_request_number,pr.ingested_at,(select count(*) from pipeline_jobs j where j.pipeline_run_id=pr.id),(select count(*) from pipeline_steps s join pipeline_jobs j on s.pipeline_job_id=j.id where j.pipeline_run_id=pr.id) from pipeline_runs pr join repositories r on r.id=pr.repository_id where pr.id=?",rs->{if(!rs.next())throw new IllegalArgumentException("Pipeline run "+id+" was not found.");return new PipelineRunResponse((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getLong(5),rs.getInt(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),(Long)rs.getObject(11),rs.getInt(13),rs.getInt(14),rs.getObject(12,java.time.Instant.class));},id);}
}
